        case 0x00: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x01: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x02: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x03: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x04: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x05: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x06: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x07: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x08: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x09: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x0a: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x0b: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x0c: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x0d: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x0e: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x0f: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x10: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x11: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x12: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x13: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x14: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x15: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x16: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x17: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x18: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x19: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x1a: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x1b: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x1c: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x1d: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x1e: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x1f: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x20: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x21: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x22: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x23: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x24: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x25: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x26: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x27: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x28: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x29: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x2a: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x2b: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x2c: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x2d: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x2e: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x2f: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x30: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x31: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x32: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x33: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x34: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x35: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x36: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x37: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x38: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x39: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x3a: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x3b: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x3c: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x3d: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x3e: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x3f: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x40: /* in b,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(BC_H, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x41: /* out (c),b */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, BC_H);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x42: /* sbc hl,bc */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_sbc_r16_r16(HL_W, BC_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x43: /* ld (nn),bc */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_ind_i16_r16(BC_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x44: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x45: /* retn */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_retn();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x46: /* im 0 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_0();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x47: /* ld i,a */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (9 - 4);
                m_ld_i_a();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x48: /* in c,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(BC_L, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x49: /* out (c),c */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x4a: /* adc hl,bc */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_adc_r16_r16(HL_W, BC_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x4b: /* ld bc,(nn) */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_r16_ind_i16(BC_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x4c: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x4d: /* reti */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_reti();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x4e: /* im 0/1 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_3();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x4f: /* ld r,a */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (9 - 4);
                m_ld_r_a();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x50: /* in d,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(DE_H, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x51: /* out (c),d */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, DE_H);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x52: /* sbc hl,de */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_sbc_r16_r16(HL_W, DE_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x53: /* ld (nn),de */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_ind_i16_r16(DE_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x54: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x55: /* retn */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_retn();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x56: /* im 1 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_1();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x57: /* ld a,i */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (9 - 4);
                m_ld_a_i();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x58: /* in e,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(DE_L, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x59: /* out (c),e */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, DE_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x5a: /* adc hl,de */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_adc_r16_r16(HL_W, DE_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x5b: /* ld de,(nn) */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_r16_ind_i16(DE_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x5c: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x5d: /* reti */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_reti();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x5e: /* im 2 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_2();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x5f: /* ld a,r */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (9 - 4);
                m_ld_a_r();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x60: /* in h,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(HL_H, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x61: /* out (c),h */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, HL_H);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x62: /* sbc hl,hl */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_sbc_r16_r16(HL_W, HL_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x63: /* ld (nn),hl */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_ind_i16_r16(HL_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x64: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x65: /* retn */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_retn();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x66: /* im 0 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_0();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x67: /* rrd */
            {
                const uint32_t m_cycles = (5 - 1);
                const uint32_t t_states = (18 - 4);
                m_rrd();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x68: /* in l,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(HL_L, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x69: /* out (c),l */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, HL_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x6a: /* adc hl,hl */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_adc_r16_r16(HL_W, HL_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x6b: /* ld hl,(nn) */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_r16_ind_i16(HL_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x6c: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x6d: /* reti */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_reti();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x6e: /* im 0/1 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_3();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x6f: /* rld */
            {
                const uint32_t m_cycles = (5 - 1);
                const uint32_t t_states = (18 - 4);
                m_rld();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x70: /* in f,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(AF_L, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x71: /* out (c),f */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, AF_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x72: /* sbc hl,sp */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_sbc_r16_r16(HL_W, SP_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x73: /* ld (nn),sp */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_ind_i16_r16(SP_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x74: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x75: /* retn */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_retn();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x76: /* im 1 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_1();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x77: /* nop */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_nop();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x78: /* in a,(c) */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_in_r08_ind_r08(AF_H, BC_L);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x79: /* out (c),a */
            {
                const uint32_t m_cycles = (3 - 1);
                const uint32_t t_states = (12 - 4);
                m_out_ind_r08_r08(BC_L, AF_H);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x7a: /* adc hl,sp */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (15 - 4);
                m_adc_r16_r16(HL_W, SP_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x7b: /* ld sp,(nn) */
            {
                const uint32_t m_cycles = (6 - 1);
                const uint32_t t_states = (20 - 4);
                m_ld_r16_ind_i16(SP_W);
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x7c: /* neg */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_neg();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x7d: /* reti */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (14 - 4);
                m_reti();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x7e: /* im 2 */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_im_2();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x7f: /* nop */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_nop();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x80: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x81: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x82: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x83: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x84: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x85: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x86: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x87: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x88: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x89: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x8a: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x8b: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x8c: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x8d: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x8e: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x8f: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x90: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x91: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x92: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x93: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x94: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x95: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x96: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x97: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x98: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x99: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x9a: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x9b: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x9c: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x9d: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x9e: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0x9f: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa0: /* ldi */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_ldi();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa1: /* cpi */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_cpi();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa2: /* ini */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_ini();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa3: /* outi */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_outi();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa4: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa5: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa6: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa7: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa8: /* ldd */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_ldd();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xa9: /* cpd */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_cpd();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xaa: /* ind */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_ind();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xab: /* outd */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_outd();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xac: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xad: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xae: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xaf: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb0: /* ldir */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_ldir();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb1: /* cpir */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_cpir();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb2: /* inir */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_inir();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb3: /* otir */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_otir();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb4: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb5: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb6: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb7: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb8: /* lddr */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_lddr();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xb9: /* cpdr */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_cpdr();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xba: /* indr */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_indr();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xbb: /* otdr */
            {
                const uint32_t m_cycles = (4 - 1);
                const uint32_t t_states = (16 - 4);
                m_otdr();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xbc: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xbd: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xbe: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xbf: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc0: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc1: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc2: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc3: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc4: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc5: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc6: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc7: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc8: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xc9: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xca: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xcb: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xcc: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xcd: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xce: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xcf: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd0: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd1: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd2: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd3: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd4: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd5: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd6: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd7: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd8: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xd9: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xda: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xdb: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xdc: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xdd: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xde: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xdf: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe0: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe1: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe2: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe3: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe4: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe5: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe6: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe7: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe8: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xe9: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xea: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xeb: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xec: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xed: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xee: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xef: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf0: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf1: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf2: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf3: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf4: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf5: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf6: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf7: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf8: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xf9: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xfa: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xfb: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xfc: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xfd: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xfe: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
        case 0xff: /* illegal */
            {
                const uint32_t m_cycles = (2 - 1);
                const uint32_t t_states = (8 - 4);
                m_illegal_ed();
                m_consume(m_cycles, t_states);
            }
            break;
